name: flow
description: Music Player app using Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  just_audio: ^0.9.34
  on_audio_query: ^2.9.0
  permission_handler: ^10.3.0
  get_it: ^7.6.0
  marquee: ^2.2.3
  scroll_to_index: ^3.0.1
  azlistview: ^2.0.0
  audio_service: ^0.18.10
  scrollable_positioned_list: ^0.2.3
  vs_scrollbar: ^0.2.1
  draggable_scrollbar: ^0.1.0
  lottie: ^2.4.0
  # Hive Dependency
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # for OS -Specific directory paths
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.1
  audio_waveforms: ^1.0.4
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # hive builder
  hive_generator: ^2.0.0
  build_runner: ^2.4.4

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#343a40"
  image: "assets/images/flow_logo.png"
  android_12:
    color: "#ffffff"
    color_dark: "#343a40"
    image: "assets/images/flow_logo.png"
  android: true
  ios: true
  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_black.ttf
        - asset: assets/fonts/poppins_bold.ttf
        - asset: assets/fonts/poppins_extra_bold.ttf
        - asset: assets/fonts/poppins_extra_light.ttf
        - asset: assets/fonts/poppins_light.ttf
        - asset: assets/fonts/poppins_medium.ttf
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_semi_bold.ttf
        - asset: assets/fonts/poppins_thin.ttf
