name: flow
description: Music Player app using Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  just_audio: ^0.9.34
  on_audio_query: ^2.9.0
  permission_handler: ^10.3.0
  get_it: ^7.6.0
  marquee: ^2.2.3
  scroll_to_index: ^3.0.1
  azlistview: ^2.0.0
  audio_service: ^0.18.10
  scrollable_positioned_list: ^0.2.3
  vs_scrollbar: ^0.2.1
  draggable_scrollbar: ^0.1.0
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_black.ttf
        - asset: assets/fonts/poppins_bold.ttf
        - asset: assets/fonts/poppins_extra_bold.ttf
        - asset: assets/fonts/poppins_extra_light.ttf
        - asset: assets/fonts/poppins_light.ttf
        - asset: assets/fonts/poppins_medium.ttf
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_semi_bold.ttf
        - asset: assets/fonts/poppins_thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
